title: MakerLabs26 - Course
description: Everything you need to participate in MakerLabs
theme: just-the-docs

url: https://UCDElecSoc.github.io/MakerLabs26


# For copy button on code
enable_copy_code_button: true

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

callouts_level: quiet # or loud

# Callout Configuration (any changes require reserve Jekyll build)
callouts:
  warning:
    title: âš ï¸ Warning!
    color: red
  troubleshooting:
    title: ğŸ˜µâ€ğŸ’« Troubleshooting...
    color: yellow
  tip:
    title: ğŸ’¡ Tip!
    color: blue
  challenge:
    title: ğŸ’ª Challenge!
    color: green
  try:
    title: ğŸ¤” Try it!
    color: green
  think:
    title: ğŸ§  Think!
    color: purple
  extra:
    title: ğŸ¤“ Umm actually..
    color: grey-lt

